name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"

      - name: Install dependencies
        run: npm install

      - name: Change working directory serverside
        run: cd serverside

      - name: Run tests
        run: npm test
